title: "So you want to train at Black Hat (or other conferences)?"
description: | 
    This is a series of articles about our experiences submitting, preparing and delivering training at Black Hat (and other conferences as well).
    <br /><br />
    It has been quite the journey and it feels like we learnt a lot of things which were not obvious to us at the beginning or were just not documented.
    <br /><br />
    In this series, we will try to set this information out in an organized way to hopefully help people in the future who are interested in going through a similar journey.
sections:
  - label: 
    items:
      - title: "So, you want to train at Black Hat? An Introduction"
      - title: Who am I, what is my motivation?